server:
  port: 8082

spring:
  application:
    name: department-service

  datasource:
    url: jdbc:mysql://localhost:3306/department_management_db
    username: root
    password: Nirjan@2503
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
